name: moldiff
channels:
  - pytorch
  - pyg
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch>=1.9.0
  - torchvision>=0.10.0
  - numpy>=1.21.0
  - matplotlib>=3.4.0
  - scikit-learn>=1.0.0
  - pandas>=1.3.0
  - tqdm>=4.62.0
  - pyyaml>=5.4.0
  - tensorboard>=2.7.0
  - jupyter>=1.0.0
  - pytest>=6.2.0
  - pytest-cov>=2.12.0
  - black>=21.0.0
  - flake8>=3.9.0
  - pyg::torch-geometric>=2.0.0
  - pip
  - pip:
    - deepchem>=2.7.0
    - rdkit-pypi>=2021.9.4
    - sphinx>=4.0.0
    - sphinx-rtd-theme>=0.5.0